TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

SHORT_LINK_CODE_MAX_LENGTH = 16
SHORT_LINK_CODE_LENGTH = 6

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
